#define LED_COUNT 93
#define LED_PIN 5
#define CURRENT_LIMIT_LED 1000

#define PERIOD_HEARTBEAT 10000
#define PERIOD_NTP_UPDATE 60000
#define PERIOD_CLOCK_UPDATE 20
#define PERIOD_LED_UPDATE 20
#define PERIOD_NIGHTMODE_CHECK 20000
#define PERIOD_BACKGROUND_RANDOM 1000

#define EEPROM_SIZE 30      // size of EEPROM to save persistent variables
#define ADR_NM_START_H 0
#define ADR_NM_END_H 4
#define ADR_NM_START_M 8
#define ADR_NM_END_M 12
#define ADR_BRIGHTNESS_BACKGROUND 16
#define ADR_BRIGHTNESS_TIME 17
#define ADR_BG_RED 21
#define ADR_BG_GREEN 22
#define ADR_BG_BLUE 23
#define ADR_TI_RED 24
#define ADR_TI_GREEN 25
#define ADR_TI_BLUE 26
